baseUrl: $JAREDBUDLONG_SITE_URL
enabled: '1'
handle: jaredbudlong
hasUrls: true
language: en-US
name: jaredbudlong
primary: false
<<<<<<< HEAD
siteGroup: 1c2d5d1f-ad2c-4985-8ed1-5fcd88a96094 # Default
=======
siteGroup: 1c2d5d1f-ad2c-4985-8ed1-5fcd88a96094 # adoc-co
>>>>>>> 9de14736472c24b8e529fc52fa2da8c1dec01949
sortOrder: 2
