fieldLayouts:
  ff7ea34a-0766-41a0-b322-c3636ca155e7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ff4d4bd6-d954-43a6-9fbd-83e1750c5478
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b49f72e-0eb0-4418-bb97-2fb50caf172a # Note+
            instructions: 'Use this to give the general public instructions on what to do to help out. '
            label: 'Instructions for the Public'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d73ee32-07f3-4edc-8e1c-7497b044f943
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93010df4-31e0-48a6-b7d0-e3d3f97cbd00
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a6eec7ea-6581-4bdf-af3d-cbef7b28b567 # Points of Contact
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34239f32-e0be-4fa3-822a-c95b7d13af1e
            userCondition: null
            warning: null
            width: 100
        name: Contacts
        uid: deeb64f0-5611-4289-be42-5ce6bda9a549
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3df31a47-abd9-48f5-b236-0d7178731bfb # Note
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7d4423e-4734-42aa-b756-4f2d25033df5
            userCondition: null
            warning: null
            width: 100
        name: Deprecating
        uid: dc7eed3d-4ef0-4ddf-ad83-7a90d6d84c0c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 0f2073bd-978b-45da-ada7-652d44935585 # Call to Action
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{associateHuman}-{dateOfStatus}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
