fieldLayouts:
  e913ac2d-c7d5-4be7-a35a-bfae8610647a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7004624b-eb4d-4bed-81f5-e37574704b29
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 767004c4-3598-46a3-ad68-bdfb06930ab5 # Contacts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 162965cb-9445-4f16-843b-15d21857fdb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3df31a47-abd9-48f5-b236-0d7178731bfb # Note
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a5ac478-e6ac-45bf-b511-a4260957072a
            userCondition: null
            warning: null
            width: 100
        name: Details
        uid: 353593fe-7e04-4a84-9e2b-4330cd22887f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 618ad16d-5035-4fbe-967a-2caf444256d9 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63d3334e-84b0-49d6-95bd-ca07439dcb68
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d3ad6ba-4819-4bba-ad5a-0ea7eba95175 # Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 969a34a2-6027-4b3b-8493-ba0c5f588c25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 610bfe49-b3ec-40ee-8377-62b1f63a8539 # Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40cbc4be-3ee0-4bdf-be16-7b5aecc146cd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b543804-c719-40ae-9f99-ca7356950124 # Address 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5f3d1bb-c89e-400a-b279-a9992423b706
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d8a0be5-824b-40ba-8e7d-25573f254bd5 # Address 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fafed63c-8ad7-4a2a-a43c-0006abbb67f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5710c8e1-8eb6-40ef-b0c7-5d0a27828c4e # City
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd44ba60-b030-468a-b650-780c95eb48d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 22cd2e0e-1a9e-49f6-9a72-31a17bbc6b27 # State
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57349218-4e70-44f0-8672-80bcc50d6543
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4064d00f-1ded-45d2-9032-e6385e7bdc36 # ZIP
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b652b97c-6302-4356-b5c1-ea89011fa666
            userCondition: null
            warning: null
            width: 100
        name: Info
        uid: b23533a7-d81d-4b74-880d-50adcd3f5ce9
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 0b837dae-5965-4957-abf2-903eccda8b7b # Facility
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
