fieldLayouts:
  f9313ee4-08ff-4d6f-864a-a825db00e265:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d41d4db-e0aa-4076-8b64-48e25e29f711
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed7cd37c-e890-4e7a-83d4-3b0990575211 # Social Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81ce6905-b883-49d6-884a-378ac2df5a4d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 610bfe49-b3ec-40ee-8377-62b1f63a8539 # Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bda7e156-8d5b-4b0a-8def-70af59dea55f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f937e62-a0bf-4fd8-aab0-98bb79a131b7
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: becc8c09-e2cc-4316-bfe4-614c5d4e708a # Social Media
sortOrder: 1
titleFormat: '{socialIcon}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
