<<<<<<< HEAD
headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
toolbar:
  - heading
  - '|'
  - bold
  - italic
=======
headingLevels: false
listPlugin: List
name: Simple
toolbar:
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
>>>>>>> 9de14736472c24b8e529fc52fa2da8c1dec01949
  - link
