css: ".btn-outline {\r\n  background-color: unset;\r\n  border: 2px;\r\n  border-color: gray;\r\n}"
headingLevels:
  - 2
  - 3
  - 4
name: 'Content Builder'
options:
  alignment:
    options:
      - left
      - center
      - right
      - justify
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  heading:
    options:
      -
        class: ck-heading
        model: heading3
        title: 'Heading 3'
        view: h3
      -
        class: ck-heading
        model: heading2
        title: 'Heading 2'
        view: h2
      -
        class: ck-heading
        model: heading4
        title: 'Heading 4'
        view: h4
  htmlSupport:
    allow:
      -
        name: img
        styles: true
      -
        classes:
          - img-float
        name: img
  image:
    toolbar:
      - transformImage
      - '|'
      - 'imageStyle:wrapText'
      - 'imageStyle:breakText'
      - '|'
      - 'imageStyle:blue'
      - '|'
      - toggleImageCaption
      - imageTextAlternative
      - '|'
      - linkImage
  link:
    addTargetToExternalLinks: true
    decorators:
      underline: 'true'
  list:
    properties:
      reversed: true
      startIndex: true
      styles: true
  style:
    definitions:
      -
        classes:
          - ck-altH2
        element: h2
        name: 'Alt H2'
      -
        classes:
          - ck-altH3
        element: h3
        name: 'Alt H3'
      -
        classes:
          - ck-altH4
        element: h4
        name: 'Alt H4'
      -
        classes:
          - btn
          - btn-solid
        element: a
        name: 'Button (Solid)'
      -
        classes:
          - btn
          - btn-outline
        element: a
        name: 'Button (Outline)'
toolbar:
  - heading
  - style
  - '|'
  - bold
  - italic
  - link
  - alignment
  - underline
  - strikethrough
  - subscript
  - superscript
  - fontSize
  - fontFamily
  - insertImage
  - mediaEmbed
  - blockQuote
  - bulletedList
  - numberedList
  - outdent
  - indent
  - todoList
  - horizontalLine
  - findAndReplace
