field: a6eec7ea-6581-4bdf-af3d-cbef7b28b567 # Points of Contact
fieldLayouts:
  f03bcdd6-6f6d-42e6-a697-ed2d2fcd1be7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1591ee1d-3fff-4d58-aa18-a10a988f4462 # Contact First Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0beea4ef-1d23-4a67-9e51-0be60a7a5b3f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fde6ec4d-b9e8-4718-a4c3-a3cc7f3957fd # Contact Last Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb8f7157-e839-43ad-92b0-99622414cc45
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 56898fae-77df-4fb1-a7eb-33b9bc015925 # Contact Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10c50306-6606-41b8-9d64-0429e7055548
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8b01bdc4-ad2a-41af-876d-c94f8cd4c5a6 # Contact Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2181046a-4090-412e-bbef-f7ae619f3c30
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 458c0316-90ec-4678-b3f1-132b8023e6cd # Organization Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e3c7f2a-c4a4-4bc5-b898-b342f92822f5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 13d89986-9f89-4f72-8911-f1dbcadda645 # Organization Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76ba0514-5a62-435d-9919-04d35aa1420d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: baa54619-b8c5-4c54-b38a-18a93980b2de # Organization Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 974a119b-1e49-4b8a-ad9d-aea7d3103aec
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 56623e2b-7fb6-41f2-8e12-a635cbc2522a # Organization Note
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca41c909-1bfb-400e-a659-87458727c041
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4461792c-7e9f-409c-b6b8-5e6c5e7e074c
        userCondition: null
fields:
  8b01bdc4-ad2a-41af-876d-c94f8cd4c5a6: # Contact Email
    columnSuffix: tfwkdmrc
    contentColumnType: string(255)
    fieldGroup: null
    handle: contactEmail
    instructions: 'Must be a valid email address.'
    name: 'Contact Email'
    searchable: true
    settings:
      maxLength: 255
      types:
        - email
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  13d89986-9f89-4f72-8911-f1dbcadda645: # Organization Website
    columnSuffix: yusmgnhr
    contentColumnType: string(255)
    fieldGroup: null
    handle: organizationWebsite
    instructions: 'Use the full website URL (including http:// or https://)'
    name: 'Organization Website'
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  458c0316-90ec-4678-b3f1-132b8023e6cd: # Organization Name
    columnSuffix: pojumnwc
    contentColumnType: text
    fieldGroup: null
    handle: organizationName
    instructions: 'FBI, ADOC, Legal Offices of XYZ, etc...'
    name: 'Organization Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  1591ee1d-3fff-4d58-aa18-a10a988f4462: # Contact First Name
    columnSuffix: ntrznmyb
    contentColumnType: text
    fieldGroup: null
    handle: contactFirstName
    instructions: null
    name: 'Contact First Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  56623e2b-7fb6-41f2-8e12-a635cbc2522a: # Organization Note
    columnSuffix: mufbkteh
    contentColumnType: string(720)
    fieldGroup: null
    handle: organizationNote
    instructions: 'This a plain text field meant for a short bit of info about the organization or contact if relevant to the CTA.'
    name: 'Organization Note'
    searchable: true
    settings:
      byteLimit: null
      charLimit: 180
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  56898fae-77df-4fb1-a7eb-33b9bc015925: # Contact Phone
    columnSuffix: qyiaiuej
    contentColumnType: string(255)
    fieldGroup: null
    handle: contactPhone
    instructions: 'Must be a valid phone 10-digit number.'
    name: 'Contact Phone'
    searchable: true
    settings:
      maxLength: 255
      types:
        - tel
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  baa54619-b8c5-4c54-b38a-18a93980b2de: # Organization Phone
    columnSuffix: dcepygcr
    contentColumnType: string(255)
    fieldGroup: null
    handle: organizationPhone
    instructions: 'Must be a valid phone 10-digit number.'
    name: 'Organization Phone'
    searchable: true
    settings:
      maxLength: 255
      types:
        - tel
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  fde6ec4d-b9e8-4718-a4c3-a3cc7f3957fd: # Contact Last Name
    columnSuffix: bcaiwqqk
    contentColumnType: text
    fieldGroup: null
    handle: contactLastName
    instructions: null
    name: 'Contact Last Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: contactBlock
name: Contact
sortOrder: 1
