field: a6eec7ea-6581-4bdf-af3d-cbef7b28b567 # Points of Contact
fieldLayouts:
  623e1d5b-1d7a-4f8a-a644-577125f752b8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5f5c9d04-ed1b-4bc0-a0ff-e33edb4650ad # Facilities
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae41241e-56c0-479f-b1f6-e3fa1a142e47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02a60f3f-fbd6-4c88-83b1-9704f13e1bee
        userCondition: null
fields:
  5f5c9d04-ed1b-4bc0-a0ff-e33edb4650ad: # Facilities
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: facilities
    instructions: null
    name: Facilities
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\fields\conditions\EmptyFieldConditionRule
                  -
                    - uid
                    - d85d7449-0e08-4df0-99ba-61868a797d76
                  -
                    - operator
                    - notempty
                  -
                    - fieldUid
                    - 767004c4-3598-46a3-ad68-bdfb06930ab5 # Contacts
      selectionLabel: 'Associate a Facility'
      showSiteMenu: false
      sources:
        - 'section:0b837dae-5965-4957-abf2-903eccda8b7b' # Facility
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: facilitiesBlock
name: Facilities
sortOrder: 2
