field: 91c6f07a-7f7f-45a4-85ac-d2ea458da892 # Link Builder
fieldLayouts:
  6a59de4f-e31e-4dd7-a5d9-685cc97bf572:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 45bbcd4e-abac-46d7-affe-24ad296b740f # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9010b8a-2041-4974-89af-a5769a49dfb6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f3a2af6-b66f-4435-95b0-75f4fbcbcdb5 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b98c16cb-f53d-418e-96e7-9e1dd22f2c35
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bae2b6be-49a5-4434-b7f8-be5a3fd5ee44
        userCondition: null
fields:
  8f3a2af6-b66f-4435-95b0-75f4fbcbcdb5: # Text
    columnSuffix: jjaffhin
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  45bbcd4e-abac-46d7-affe-24ad296b740f: # Heading
    columnSuffix: ammlydbt
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 1
