columnSuffix: ldvdehtx
contentColumnType: integer(10)
fieldGroup: 83ab8938-f287-4a0d-9365-f010ed540e4d # Humans
handle: ais
instructions: null
name: 'AIS#'
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
