columnSuffix: null
contentColumnType: string
fieldGroup: 83ab8938-f287-4a0d-9365-f010ed540e4d # Humans
handle: associateCTA
instructions: 'previously "associateHuman"'
name: 'Associate CTA'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 0
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Associate a Human'
  showSiteMenu: false
  sources:
    - 'section:0f2073bd-978b-45da-ada7-652d44935585' # Call to Action
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
