columnSuffix: enbuduhd
contentColumnType: text
fieldGroup: 4cda9b6f-f2fa-44ce-bc23-2c1b24cc4b1d # Common
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: d4091260-2611-458d-b5d5-55c79aa86a96
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
