columnSuffix: null
contentColumnType: string
fieldGroup: 260e937f-426c-4da5-b2d4-260e4c279ebf # Facilities
handle: contacts
instructions: null
name: Contacts
searchable: true
settings:
  contentTable: '{{%matrixcontent_contacts}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
