columnSuffix: dynohchc
contentColumnType: string(255)
fieldGroup: 4cda9b6f-f2fa-44ce-bc23-2c1b24cc4b1d # Common
handle: email
instructions: null
name: Email
searchable: true
settings:
  maxLength: 255
  types:
    - email
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
