columnSuffix: mfjwvggk
contentColumnType: text
fieldGroup: 83ab8938-f287-4a0d-9365-f010ed540e4d # Humans
handle: middleName
instructions: null
name: 'Middle Name'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
