columnSuffix: null
contentColumnType: string
fieldGroup: 83ab8938-f287-4a0d-9365-f010ed540e4d # Humans
handle: reports
instructions: null
name: Reports
searchable: true
settings:
  contentTable: '{{%matrixcontent_reports}}'
  maxBlocks: null
  minBlocks: 0
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
