columnSuffix: prjznyon
contentColumnType: text
fieldGroup: cbe20d08-1e17-4b90-83f6-66c02103f74f # Address
handle: zip
instructions: null
name: ZIP
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: '12345'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
