defaultPlacement: end
enableVersioning: true
handle: callToAction
name: 'Call to Action'
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
