defaultPlacement: end
enableVersioning: true
handle: humanList
name: 'Humans List'
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: true
    template: human/_list.twig
    uriFormat: humans
type: single
