defaultPlacement: end
enableVersioning: true
handle: reportType
name: 'Report Type'
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: true
    template: report-type/_entry
    uriFormat: 'report-type/{slug}'
type: channel
