columnSuffix: aziegvte
contentColumnType: text
fieldGroup: 4cda9b6f-f2fa-44ce-bc23-2c1b24cc4b1d # Common
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: ca4c17b0-5cc3-4db6-a1e7-e40c86f224ab # Content Builder
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
