columnSuffix: yqykfvgg
contentColumnType: datetime
fieldGroup: 83ab8938-f287-4a0d-9365-f010ed540e4d # Humans
handle: dateOfDeath
instructions: null
name: 'Date of Death'
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
