columnSuffix: null
contentColumnType: string
fieldGroup: cbe20d08-1e17-4b90-83f6-66c02103f74f # Address
handle: linkBuilder
instructions: null
name: 'Link Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_linkbuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
