columnSuffix: null
contentColumnType: string
fieldGroup: 83ab8938-f287-4a0d-9365-f010ed540e4d # Humans
handle: photos
instructions: 'The photos will be displayed in order shown. The first image will be used for larger displays or when only one image can be shown.'
name: Photo(s)
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:3719fbc3-056c-4ca7-b8fd-8e2049c14a58' # ADOC Images
  defaultUploadLocationSubpath: '{section}'
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:e170055a-d66a-4ff3-ae78-b62e4de3fe25' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add image(s)'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:3719fbc3-056c-4ca7-b8fd-8e2049c14a58' # ADOC Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
