dateModified: 1688590091
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      key: 'section:4118eb52-3c43-406c-bf9f-01c4542c8331' # Cause of Death
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:0b837dae-5965-4957-abf2-903eccda8b7b' # Facility
      tableAttributes:
        - postDate
        - dateUpdated
        - slug
        - 'field:610bfe49-b3ec-40ee-8377-62b1f63a8539' # Website
        - 'field:618ad16d-5035-4fbe-967a-2caf444256d9' # Email
        - 'field:9b543804-c719-40ae-9f99-ca7356950124' # Address 1
        - 'field:5710c8e1-8eb6-40ef-b0c7-5d0a27828c4e' # City
        - 'field:22cd2e0e-1a9e-49f6-9a72-31a17bbc6b27' # State
        - 'field:4064d00f-1ded-45d2-9032-e6385e7bdc36' # ZIP
        - 'field:3df31a47-abd9-48f5-b236-0d7178731bfb' # Note
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:f623b9fa-1630-45e7-980d-89b2b18cd869' # Humans
      tableAttributes:
        - 'field:18f58c1c-5fe3-4755-b144-58ecd20650e3' # AIS#
        - 'field:08d0c3ed-94bf-4311-a7a5-c99f216a0217' # Photo(s)
        - postDate
        - 'field:208f9b3c-0d64-40df-8ac3-bb5d65015616' # Date of Death
        - dateUpdated
        - 'field:3df31a47-abd9-48f5-b236-0d7178731bfb' # Note
        - 'field:f3880a1b-da42-49af-98fc-a3c6da5f1c7e' # Facility
        - 'field:cccb7bc7-0136-4564-86ca-5da3adfb5f88' # Cause of Death
        - link
      type: native
    -
      key: 'section:7e4960eb-d761-4dfa-b93d-58db38369abd' # Report Type
      type: native
    -
      heading: ''
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:2016e348-9fd6-4b38-83b2-8257ad98ee78' # Navigation
      tableAttributes:
        - postDate
        - type
        - dateUpdated
        - 'field:05fd0cd6-a8af-4734-90bf-6131cbedfbe1' # Internal Link
        - 'field:610bfe49-b3ec-40ee-8377-62b1f63a8539' # Website
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      key: 'section:becc8c09-e2cc-4316-bfe4-614c5d4e708a' # Social Media
      type: native
    -
      key: 'section:b90fb7c4-b0d0-41be-afe9-d736a6e74113' # Pages
      type: native
email:
  fromEmail: noreply@sotnf.com
  fromName: SOTNF
  replyToEmail: info@sotnf.com
  template: ''
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_API_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  adocImages:
    hasUrls: true
    name: 'ADOC Images'
    settings:
      path: '@webroot/assets/uploads/adoc_images'
    type: craft\fs\Local
    url: '@webADOC/assets/uploads/adoc_images'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/uploads/images'
    type: craft\fs\Local
    url: '@web/assets/uploads/images'
  socialIcons:
    hasUrls: true
    name: 'Social Icons'
    settings:
      path: '@webroot/assets/uploads/social_icons'
    type: craft\fs\Local
    url: '@web/assets/uploads/social_icons'
meta:
  __names__:
    0b837dae-5965-4957-abf2-903eccda8b7b: Facility # Facility
    1bafe2ee-068d-459e-b936-f6fba061fcc4: 'Last Name' # Last Name
    1c2d5d1f-ad2c-4985-8ed1-5fcd88a96094: Main # Main
    1c7c1479-2d25-459a-9ed8-a59a16211c72: Default # Default
    2d0f3b72-ec6b-4c9b-8ea6-d66cf7dd996d: 'Social Media' # Social Media
    3ab0260c-3549-45c5-910d-d432011521f1: Email # Email
    3b593700-17e8-4ac2-aa10-d55f5dd6e296: Heading # Heading
    03db330d-c8e0-43d8-b1df-b19441140d21: 'Nick Name' # Nick Name
    03ddb5c9-2334-459c-b398-ce8845bca7d2: '300x200 (Crop)' # 300x200 (Crop)
    3df31a47-abd9-48f5-b236-0d7178731bfb: Note # Note
    4cda9b6f-f2fa-44ce-bc23-2c1b24cc4b1d: Common # Common
    4f8df9ae-e832-4225-9456-4ab722757c6c: Advocate # Advocate
    5d8a0be5-824b-40ba-8e7d-25573f254bd5: 'Address 2' # Address 2
    05fd0cd6-a8af-4734-90bf-6131cbedfbe1: 'Internal Link' # Internal Link
    6bc9b592-26cf-436d-a594-9e321e2334d6: 'Public Schema' # Public Schema
    6e2fc37c-e5a0-49f2-b595-2a3789708767: 'Middle Name' # Middle Name
    7babb8bc-f92d-42f6-9be7-fe2c12f147ac: adoc-co # adoc-co
    7d3ad6ba-4819-4bba-ad5a-0ea7eba95175: Phone # Phone
    7e4960eb-d761-4dfa-b93d-58db38369abd: 'Report Type' # Report Type
    08d0c3ed-94bf-4311-a7a5-c99f216a0217: Photo(s) # Photo(s)
    8dec767a-fcd4-452e-acf7-dc12519a56cc: 'Button Entry' # Button Entry
    9b543804-c719-40ae-9f99-ca7356950124: 'Address 1' # Address 1
    9d1171fc-9c98-4610-988a-dc9d91b86151: 'Last Name' # Last Name
    9e25abb4-53e1-486c-b2d7-4107ca3d6206: jaredbudlong # jaredbudlong
    9ee40c3e-c86e-4508-b0d5-d56d328b33f0: Default # Default
    17d92301-81f5-45b4-930e-0ca777b052a6: Links # Links
    18f58c1c-5fe3-4755-b144-58ecd20650e3: 'AIS#' # AIS#
    19a6fa2e-899b-4c96-a230-0f486ae0295b: 'Humans List' # Humans List
    20d641d6-60d4-41ac-873f-6e5c6f1b68a6: Small # Small
    22cd2e0e-1a9e-49f6-9a72-31a17bbc6b27: State # State
    22db129c-9898-4b4c-8f3c-9c5b73089d90: 'First Name' # First Name
    42f1b941-3332-420b-9ee9-38792ce458c1: 'Report Type' # Report Type
    44eb3684-3bb8-4859-b93d-0a245b4e98c9: sotnf # sotnf
    53d0b91e-8add-4ac6-89a0-d53e998fa5ce: 'First Name' # First Name
    53ea8e22-cc1f-4aaa-a8f5-586d3186f97d: 'Content Builder' # Content Builder
    74e97928-fd8a-43cb-bbb8-8aaf1765ec33: 'Alternate Title' # Alternate Title
    82a5588d-d60f-4a6a-895b-5896986aa54f: 'Facilities List' # Facilities List
    83ab8938-f287-4a0d-9365-f010ed540e4d: Humans # Humans
    83e8d49f-8f26-4eeb-851e-e997ee1b92cc: 'Contact Options' # Contact Options
    084e9175-1a64-407f-aaa6-371c49320c98: Medium # Medium
    89f7002a-a51c-4109-bde3-60f37881945a: Default # Default
    180a6f6d-ba8c-4567-97e5-4a0dcc491507: Phone # Phone
    208f9b3c-0d64-40df-8ac3-bb5d65015616: 'Date of Death' # Date of Death
    239d0390-17ff-4caa-a987-cc44028eb456: Text # Text
    260e937f-426c-4da5-b2d4-260e4c279ebf: Facilities # Facilities
    323be661-9ee7-4f57-976a-4a5032821248: Homepage # Homepage
    528e2427-a8c6-40bb-b462-54d99c4f0041: Large # Large
    563c0bfc-c323-44b4-864d-04e0a0bd573c: Email # Email
    610bfe49-b3ec-40ee-8377-62b1f63a8539: Website # Website
    618ad16d-5035-4fbe-967a-2caf444256d9: Email # Email
    2016e348-9fd6-4b38-83b2-8257ad98ee78: Navigation # Navigation
    3719fbc3-056c-4ca7-b8fd-8e2049c14a58: 'ADOC Images' # ADOC Images
    4064d00f-1ded-45d2-9032-e6385e7bdc36: ZIP # ZIP
    4118eb52-3c43-406c-bf9f-01c4542c8331: 'Cause of Death' # Cause of Death
    5710c8e1-8eb6-40ef-b0c7-5d0a27828c4e: City # City
    93574e3b-a524-4c0e-b469-18cbecc93c3a: 'Title Tag' # Title Tag
    294120a9-281c-498c-8a1f-ac5584122b2c: Text # Text
    583847b3-88c3-4e76-80c7-0e070db0bf98: XSmall # XSmall
    767004c4-3598-46a3-ad68-bdfb06930ab5: Contacts # Contacts
    59884906-b9a5-4c4e-95b4-6a861d2af939: Warden # Warden
    a5dcdf8e-bcad-4699-9afc-1c6b48ddaf50: 'Share Image' # Share Image
    a112a8f4-4945-4b9a-8f3e-8e4568e6a339: Entry # Entry
    a70227e0-2eb4-4b19-b0b1-7c0a1349c7fb: 'Meta Description' # Meta Description
    ada94301-769d-488e-9cb8-c05c292d9509: ADOC-Import # ADOC-Import
    adced8d4-609c-4743-b767-79951d8febb2: Website # Website
    b0afcc54-8f8c-4591-a381-47849a7f1739: Report # Report
    b7f745a8-d92f-4477-a982-2796a52d6ba3: Simple # Simple
    b36b4142-8b37-464c-b6f7-153c434b90c6: 'Last Name' # Last Name
    b90fb7c4-b0d0-41be-afe9-d736a6e74113: Pages # Pages
    baef7271-cefd-4dab-8b7a-6fde35a5c8cb: Default # Default
    bc5220fc-108c-44de-8be3-a34801b4047d: Phone # Phone
    becc8c09-e2cc-4316-bfe4-614c5d4e708a: 'Social Media' # Social Media
    bf2ef742-4173-46ec-b7c3-ff0e3fff1f8e: Default # Default
    c18a2ab5-3e10-4b24-905b-13afc46a454a: 'Button URL' # Button URL
    c506c8b9-2ee8-49d6-8734-615445bf46b1: 'Alternate Headline' # Alternate Headline
    c2553642-988b-4223-9fd2-37d5d996a02d: 'Facilities List' # Facilities List
    c9403425-dcc5-44fc-a5b9-73cf175adb5b: Nickname # Nickname
    ca4c17b0-5cc3-4db6-a1e7-e40c86f224ab: 'Content Builder' # Content Builder
    cbe20d08-1e17-4b90-83f6-66c02103f74f: Address # Address
    cccb7bc7-0136-4564-86ca-5da3adfb5f88: 'Cause of Death' # Cause of Death
    cdae8b0b-b588-4459-8b32-59a376d0d453: 'Button Text' # Button Text
    ce477fbc-eb08-4203-9540-b206a59fe09d: 'First Name' # First Name
    d06d2a22-6403-454d-97d9-c6581c1e9639: Default # Default
    d3c9ee5b-6826-4dd6-8ae6-b12ecd483794: Email # Email
    d512eaa2-6ab2-428b-9f73-edf2b098e930: 'Social Media' # Social Media
    da98bab4-69f8-4168-b0bb-18e3b1405043: 'First Name' # First Name
    deacb3ec-310f-4577-9d5d-933ea4b08178: Phone # Phone
    e5affbb1-ce5b-4a8f-a04c-b64edca2e94e: Homepage # Homepage
    e54fbb1c-4ada-45eb-85b1-5ff583ee3d8a: 'Public Schema' # Public Schema
    e170055a-d66a-4ff3-ae78-b62e4de3fe25: Images # Images
    ea2140bf-a65e-4e8f-9a7c-578b41d0fab9: External # External
    eae88fa5-67ba-48e6-b5cf-0b58ad2970d2: Entries # Entries
    ed7cd37c-e890-4e7a-83d4-3b0990575211: 'Social Icon' # Social Icon
    ee7af9cb-a346-48d2-8b00-d209e9d32aae: 'Humans List' # Humans List
    eeee74d7-7a29-4e24-8382-0fcd9da18bd3: URL # URL
    f4a9f4cd-3e3a-4cf9-89d3-fe59aba937d5: Internal # Internal
    f6d97247-dc2b-4576-bb40-a61f43a7d835: 'Last Name' # Last Name
    f7dd2378-fc93-4bf2-bd9d-e26856ca790e: Reports # Reports
    f9f27c6e-965b-4439-b418-231f96a83691: 'Link Builder' # Link Builder
    f623b9fa-1630-45e7-980d-89b2b18cd869: Humans # Humans
    f3880a1b-da42-49af-98fc-a3c6da5f1c7e: Facility # Facility
    fb009506-1583-43fb-b530-a30d8c2d523f: 'Report Link' # Report Link
    feeca86c-3550-4c62-b56c-e92a62145656: Links # Links
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: adoc-co
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
