dateModified: 1709964170
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - postDate
        - expiryDate
        - section
        - slug
        - link
        - dateUpdated
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      key: 'section:4118eb52-3c43-406c-bf9f-01c4542c8331' # Cause of Death
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:0b837dae-5965-4957-abf2-903eccda8b7b' # Facility
      tableAttributes:
        - postDate
        - dateUpdated
        - slug
        - 'field:610bfe49-b3ec-40ee-8377-62b1f63a8539' # Website
        - 'field:618ad16d-5035-4fbe-967a-2caf444256d9' # Email
        - 'field:9b543804-c719-40ae-9f99-ca7356950124' # Address 1
        - 'field:5710c8e1-8eb6-40ef-b0c7-5d0a27828c4e' # City
        - 'field:22cd2e0e-1a9e-49f6-9a72-31a17bbc6b27' # State
        - 'field:4064d00f-1ded-45d2-9032-e6385e7bdc36' # ZIP
        - 'field:3df31a47-abd9-48f5-b236-0d7178731bfb' # Note
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:f623b9fa-1630-45e7-980d-89b2b18cd869' # Humans
      tableAttributes:
        - 'field:18f58c1c-5fe3-4755-b144-58ecd20650e3' # AIS#
        - 'field:08d0c3ed-94bf-4311-a7a5-c99f216a0217' # Photo(s)
        - postDate
        - 'field:208f9b3c-0d64-40df-8ac3-bb5d65015616' # Date of Status
        - dateUpdated
        - 'field:3df31a47-abd9-48f5-b236-0d7178731bfb' # Note
        - 'field:f3880a1b-da42-49af-98fc-a3c6da5f1c7e' # Facility
        - 'field:cccb7bc7-0136-4564-86ca-5da3adfb5f88' # Cause of Death
        - link
      type: native
    -
      key: 'section:0f2073bd-978b-45da-ada7-652d44935585' # Call to Action
      type: native
    -
      key: 'section:7e4960eb-d761-4dfa-b93d-58db38369abd' # Report Type
      type: native
    -
      heading: ''
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:2016e348-9fd6-4b38-83b2-8257ad98ee78' # Navigation
      tableAttributes:
        - postDate
        - type
        - dateUpdated
        - 'field:05fd0cd6-a8af-4734-90bf-6131cbedfbe1' # Internal Link
        - 'field:610bfe49-b3ec-40ee-8377-62b1f63a8539' # Website
        - link
      type: native
    -
      heading: ''
      type: heading
    -
      heading: ''
      type: heading
    -
      key: 'section:c98d6a89-3b56-4b37-a372-766360d59c7a' # Social Media
      type: native
email:
  fromEmail: noreply@sotnf.com
  fromName: SOTNF
  replyToEmail: info@sotnf.com
  template: ''
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_API_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  adocImages:
    hasUrls: true
    name: 'ADOC Images'
    settings:
      path: '@webroot/assets/uploads/adoc_images'
    type: craft\fs\Local
    url: '@webADOC/assets/uploads/adoc_images'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/uploads/images'
    type: craft\fs\Local
    url: '@web/assets/uploads/images'
  socialIcons:
    hasUrls: true
    name: 'Social Icons'
    settings:
      path: '@webroot/assets/uploads/social_icons'
    type: craft\fs\Local
    url: '@web/assets/uploads/social_icons'
meta:
  __names__:
    0b837dae-5965-4957-abf2-903eccda8b7b: Facility # Facility
    0f2073bd-978b-45da-ada7-652d44935585: 'Call to Action' # Call to Action
    1c2d5d1f-ad2c-4985-8ed1-5fcd88a96094: adoc-co # adoc-co
    1c7c1479-2d25-459a-9ed8-a59a16211c72: Default # Default
    1c51896d-9e91-4685-9966-68859ac11b02: Default # Default
    1d74b11d-7ab2-4b65-97b3-48023ed39f23: crop450 # crop450
    3ab0260c-3549-45c5-910d-d432011521f1: Email # Email
    03db330d-c8e0-43d8-b1df-b19441140d21: 'Nick Name' # Nick Name
    3df31a47-abd9-48f5-b236-0d7178731bfb: Note # Note
    4c69b583-e820-4a1e-90ad-7231ac20d181: Default # Default
    4cda9b6f-f2fa-44ce-bc23-2c1b24cc4b1d: Common # Common
    4ce13bd8-0fb7-4a44-a95c-918922fa0f82: 'Social Icon' # Social Icon
    4f8df9ae-e832-4225-9456-4ab722757c6c: Advocate # Advocate
    5b49f72e-0eb0-4418-bb97-2fb50caf172a: 'Enhanced Note' # Enhanced Note
    5d8a0be5-824b-40ba-8e7d-25573f254bd5: 'Address 2' # Address 2
    5f5c9d04-ed1b-4bc0-a0ff-e33edb4650ad: Facilities # Facilities
    05fd0cd6-a8af-4734-90bf-6131cbedfbe1: 'Internal Link' # Internal Link
    6b9cc9c1-225b-4adf-acb3-2d09c950592d: 'Content Builder' # Content Builder
    6bc9b592-26cf-436d-a594-9e321e2334d6: 'Public Schema' # Public Schema
    6dc1cc43-84ee-4c79-9436-d83d6afec4ab: 'ADOC Help' # ADOC Help
    6e2fc37c-e5a0-49f2-b595-2a3789708767: 'Middle Name' # Middle Name
    7babb8bc-f92d-42f6-9be7-fe2c12f147ac: adoc-co # adoc-co
    7d3ad6ba-4819-4bba-ad5a-0ea7eba95175: Phone # Phone
    7d4eb720-ef43-42e4-9ed1-f3cef6aabdc0: Small # Small
    7e4960eb-d761-4dfa-b93d-58db38369abd: 'Report Type' # Report Type
    8b01bdc4-ad2a-41af-876d-c94f8cd4c5a6: 'Contact Email' # Contact Email
    08d0c3ed-94bf-4311-a7a5-c99f216a0217: Photo(s) # Photo(s)
    08d9a170-a244-494d-9f6b-43f3f973d6e0: Entry # Entry
    8f3a2af6-b66f-4435-95b0-75f4fbcbcdb5: Description # Description
    9a3df3ee-9202-4b2e-9bee-1fd7b78e832b: 'Block Style' # Block Style
    09b4fd3c-1978-4c71-9acf-e9154d9e123e: XSmall # XSmall
    9b543804-c719-40ae-9f99-ca7356950124: 'Address 1' # Address 1
    9d1171fc-9c98-4610-988a-dc9d91b86151: 'Last Name' # Last Name
    13d89986-9f89-4f72-8911-f1dbcadda645: 'Organization Website' # Organization Website
    18f58c1c-5fe3-4755-b144-58ecd20650e3: 'AIS#' # AIS#
    19a6fa2e-899b-4c96-a230-0f486ae0295b: 'Humans List' # Humans List
    22cd2e0e-1a9e-49f6-9a72-31a17bbc6b27: State # State
    42f1b941-3332-420b-9ee9-38792ce458c1: 'Report Type' # Report Type
    45bbcd4e-abac-46d7-affe-24ad296b740f: Heading # Heading
    53d0b91e-8add-4ac6-89a0-d53e998fa5ce: 'First Name' # First Name
    60e02dff-6566-4dfe-bd08-71b07a2c8123: Medium # Medium
    61b64f4c-8dec-43f2-8ce0-f44bad4431e5: 'ADOC Images' # ADOC Images
    61e6ed49-c92f-4105-96be-07ba9d6fa7e2: Simple # Simple
    70e8107c-4cfe-4296-81cb-60ea04da6dd3: 'Button URL' # Button URL
    82a5588d-d60f-4a6a-895b-5896986aa54f: 'Facilities List' # Facilities List
    83ab8938-f287-4a0d-9365-f010ed540e4d: Humans # Humans
    83e8d49f-8f26-4eeb-851e-e997ee1b92cc: 'Contact Options' # Contact Options
    89f7002a-a51c-4109-bde3-60f37881945a: Default # Default
    91c6f07a-7f7f-45a4-85ac-d2ea458da892: 'Link Builder' # Link Builder
    94d54b14-300e-4fb9-bd82-3dd86d4fffb0: Enhanced # Enhanced
    99f2ce1d-b773-4150-a39c-24863e4e70c7: 'Button Entry' # Button Entry
    186b9fb3-aa4a-40e0-8504-79beddea39d4: Links # Links
    208f9b3c-0d64-40df-8ac3-bb5d65015616: 'Date of Status' # Date of Status
    260e937f-426c-4da5-b2d4-260e4c279ebf: Facilities # Facilities
    323be661-9ee7-4f57-976a-4a5032821248: Homepage # Homepage
    458c0316-90ec-4678-b3f1-132b8023e6cd: 'Organization Name' # Organization Name
    460b4205-a4fb-4e32-9637-14b9549e10e5: Status # Status
    563c0bfc-c323-44b4-864d-04e0a0bd573c: Email # Email
    610bfe49-b3ec-40ee-8377-62b1f63a8539: Website # Website
    618ad16d-5035-4fbe-967a-2caf444256d9: Email # Email
    883ceb06-d923-4375-87ff-d2b0da252179: '300x200 Crop' # 300x200 Crop
    1591ee1d-3fff-4d58-aa18-a10a988f4462: 'Contact First Name' # Contact First Name
    2016e348-9fd6-4b38-83b2-8257ad98ee78: Navigation # Navigation
    2259f202-ccad-4b51-a3eb-8e685ab930d5: Heading # Heading
    4064d00f-1ded-45d2-9032-e6385e7bdc36: ZIP # ZIP
    4118eb52-3c43-406c-bf9f-01c4542c8331: 'Cause of Death' # Cause of Death
    5710c8e1-8eb6-40ef-b0c7-5d0a27828c4e: City # City
    56623e2b-7fb6-41f2-8e12-a635cbc2522a: 'Organization Note' # Organization Note
    56898fae-77df-4fb1-a7eb-33b9bc015925: 'Contact Phone' # Contact Phone
    729254e3-5268-4836-a893-239fb9e7988d: 'Button Style' # Button Style
    767004c4-3598-46a3-ad68-bdfb06930ab5: Contacts # Contacts
    45979944-c486-42b3-b061-050494fc7e2a: Heading # Heading
    59884906-b9a5-4c4e-95b4-6a861d2af939: Warden # Warden
    a6eec7ea-6581-4bdf-af3d-cbef7b28b567: 'Points of Contact' # Points of Contact
    a8961e26-c4b9-4c0e-9aac-c648112bf612: 'Social Media' # Social Media
    a4245537-02c5-4548-bc4d-8fc5d94435a5: Description # Description
    ad14c983-625e-43c9-8c51-c278fffb43ce: Facilities # Facilities
    adced8d4-609c-4743-b767-79951d8febb2: Website # Website
    b0afcc54-8f8c-4591-a381-47849a7f1739: Report # Report
    b0328ad7-de80-4150-8594-1431bb30a28b: Text # Text
    b36b4142-8b37-464c-b6f7-153c434b90c6: 'Last Name' # Last Name
    b60e3c63-a6f2-44c9-9561-79ef35de673a: 'Associate CTA' # Associate CTA
    b494badf-fe13-49ff-a323-3392eb161e3b: Description # Description
    b681b236-e7a0-4b70-9831-cd91e74e516f: jaredbudlong # jaredbudlong
    baa54619-b8c5-4c54-b38a-18a93980b2de: 'Organization Phone' # Organization Phone
    baef7271-cefd-4dab-8b7a-6fde35a5c8cb: Default # Default
    bc5220fc-108c-44de-8be3-a34801b4047d: Phone # Phone
    c1dc52e8-cf04-4a01-9bb9-13760ded72e0: 'Alternate Title' # Alternate Title
    c98d6a89-3b56-4b37-a372-766360d59c7a: 'Social Media' # Social Media
    c506c8b9-2ee8-49d6-8734-615445bf46b1: 'Alternate Headline' # Alternate Headline
    c2553642-988b-4223-9fd2-37d5d996a02d: 'Facilities List' # Facilities List
    c9403425-dcc5-44fc-a5b9-73cf175adb5b: Nickname # Nickname
    cb9456f3-411e-4d93-a9b6-ead966be7c52: Description # Description
    cbe20d08-1e17-4b90-83f6-66c02103f74f: Address # Address
    cccb7bc7-0136-4564-86ca-5da3adfb5f88: 'Cause of Death' # Cause of Death
    cda51961-8287-41cd-8359-84ea541a1c17: Large # Large
    ce31da6e-5e79-4935-bc5e-fdddae322eda: Heading # Heading
    ce477fbc-eb08-4203-9540-b206a59fe09d: 'First Name' # First Name
    d06d2a22-6403-454d-97d9-c6581c1e9639: Default # Default
    d9ba70d2-9b19-48d4-8565-4b3f6010bfde: 'Button URL' # Button URL
    d12b5dba-3d80-40e6-ab92-71dc0f96a5f3: Links # Links
    d4091260-2611-458d-b5d5-55c79aa86a96: 'Content Builder' # Content Builder
    da98bab4-69f8-4168-b0bb-18e3b1405043: 'First Name' # First Name
    deacb3ec-310f-4577-9d5d-933ea4b08178: Phone # Phone
    e2aedf80-f88a-4613-8c40-4124ae0fc8a6: 'Simple Note' # Simple Note
    e5affbb1-ce5b-4a8f-a04c-b64edca2e94e: Homepage # Homepage
    e7e8de3a-4e29-4d7f-a7aa-fe0caf3792df: 'Social Media' # Social Media
    e170055a-d66a-4ff3-ae78-b62e4de3fe25: Images # Images
    ea2140bf-a65e-4e8f-9a7c-578b41d0fab9: External # External
    ee7af9cb-a346-48d2-8b00-d209e9d32aae: 'Humans List' # Humans List
    f0a5a36a-d66e-4168-84a1-eb0d58dba3da: Entries # Entries
    f4a9f4cd-3e3a-4cf9-89d3-fe59aba937d5: Internal # Internal
    f6d97247-dc2b-4576-bb40-a61f43a7d835: 'Last Name' # Last Name
    f7dd2378-fc93-4bf2-bd9d-e26856ca790e: Reports # Reports
    f99acd79-41ba-458a-aa4a-75a717cbd502: Contact # Contact
    f623b9fa-1630-45e7-980d-89b2b18cd869: Humans # Humans
    f3880a1b-da42-49af-98fc-a3c6da5f1c7e: Facility # Facility
    f5000937-8c06-4b27-88a3-4e55809b1497: 'Button Label' # Button Label
    fb009506-1583-43fb-b530-a30d8c2d523f: 'Report Link' # Report Link
    fde6ec4d-b9e8-4718-a4c3-a3cc7f3957fd: 'Contact Last Name' # Contact Last Name
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: adoc-co
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Chicago
