defaultPlacement: end
enableVersioning: true
handle: facilities
name: Facilities
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: true
    template: facilities/_entry
    uriFormat: 'facilities/{slug}'
type: channel
