defaultPlacement: end
enableVersioning: true
handle: facility
name: Facility
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: true
    template: facility/_entry.twig
    uriFormat: 'facility/{slug}'
type: channel
