defaultPlacement: end
enableVersioning: true
handle: human
name: Humans
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: true
    template: human/_entry
    uriFormat: 'human/{slug}'
type: channel
