defaultPlacement: end
enableVersioning: true
handle: navigation
name: Navigation
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: eac97987-606b-4c60-904f-52b75280be08
type: structure
