defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7babb8bc-f92d-42f6-9be7-fe2c12f147ac: # adoc-co
    enabledByDefault: true
    hasUrls: true
    template: pages/_entryADOC
    uriFormat: '{slug}'
  9e25abb4-53e1-486c-b2d7-4107ca3d6206: # jaredbudlong
    enabledByDefault: true
    hasUrls: true
    template: pages/_entryJB
    uriFormat: '{slug}'
  44eb3684-3bb8-4859-b93d-0a245b4e98c9: # sotnf
    enabledByDefault: true
    hasUrls: true
    template: pages/_entrySOTNF
    uriFormat: '{slug}'
structure:
  maxLevels: 2
  uid: 92f71bf5-53bc-4aa5-835b-ac633d580524
type: structure
