version: '1'

services:
  web:
    environment:
      # DDEV Settings
      - PRIMARY_SITE_URL=${DDEV_PRIMARY_URL} 
      - CRAFT_CMD_ROOT=./craft

      # The environment Craft is currently running in (local, stage, prod, etc.)
      - CRAFT_ENVIRONMENT=local

      # The application ID used to to uniquely store session and cache data, mutex locks, and more
      - CRAFT_APP_ID=

      # The secure key Craft will use for hashing and encrypting data
      - CRAFT_SECURITY_KEY=

      # Database connection settings
      - CRAFT_DB_DRIVER="mysql"
      - CRAFT_DB_SERVER="db"
      - CRAFT_DB_PORT="3306"
      - CRAFT_DB_DATABASE="sotnfadmin_cc"
      - CRAFT_DB_USER="sotnfadmin_admin"
      - CRAFT_DB_PASSWORD="bony1-espionage-guru"

      - BASE_PATH=/var/www/html/public_html

      # General settings (see config/general.php)
      - DEV_MODE=true
      - ALLOW_ADMIN_CHANGES=true
      - DISALLOW_ROBOTS=true