name: Deploy Repository to SOTNF (Directory "$GITHUB_REF_NAME")
on:
  push:
    branches:
      - Staging
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
#      - name: Test Variable
#        run: echo "REMOTE-DIR ${{ github.ref_name }}"
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_STAGING_SERVER }}
          username: ${{ secrets.FTP_STAGING_USERNAME }}
          password: ${{ secrets.FTP_STAGING_PASSWORD }}
          server-dir: "/${{ github.ref_name }}"  # This will create a subfolder based on the branch name
